### ISSUE TITLE
Cant get current build working

### ISSUE THREAD

**Issue by brettdaman** [Agile-IoT/agile-nodered#4]
I cloned the repo, build the container with the latest build and i see in osjs when i click on nodered a black screen.
If i go to IP:1880/ i got an error stating:
> hi, you need to go to /red-agile/ and pass a token as a query argument in the url

I cant find documentation on this and have no idea how to get the new security working.

I got it working by checking out v0.1.0

**Comment by nopbyte** [comment]
hi @brettdaman,

If you checkout the latest version of the agile-stack you should also get security components that now ask you for username and password when you try to go to OS.js. Did you just checkout the latest node-red without checking out the latest agile-stack?

**Comment by brettdaman** [comment]
I checked out the latest agile-scripts, it contains agile-stack @ 7b3de1a

**Comment by nopbyte** [comment]
you would need the latest version of the stack to have security in there.

**Comment by brettdaman** [comment]
The latest agile-stack is already in agile-scripts as you can see bu the commit number above.

**Comment by cskiraly** [comment]
I have changed agile-script to be a simple placeholder for agile-cli and agile-stack. This is in order to avoid having 2 places where we maintain stuff. We could also decide to drop agile-scripts, but it was the reasonable upgrade path for those that already have it.
https://github.com/Agile-IoT/agile-scripts/tree/v0.1.3 is a coherent set of cli and stack. And that stack points only to versioned images, so that you download a coherent set of images.
If you clone one of the components, take its master, and build it, you get a newer version. This might not work (like in your case). You have to set the component to the same versioned tag.

We could do more to help:
- we could maintain a repo with submodules of all components at the correct versions. I'm not sure we want this, even if that would be coherent
- we could use git URLs in the docker-compose.yml "build:" lines. This is possible, we are not doing it because resin.os has no git installed, this it was not working there.

**Comment by brettdaman** [comment]
Its working
