### ISSUE TITLE
NodeRed UI and dashboard not visible 

### ISSUE THREAD

**Issue by dpap** [Agile-IoT/agile-nodered#6]
on latest agile-nodered nodered (agileiot/agile-nodered-x86_64) UI and dashboard do not work. Selecting nodered UI and Dashboard from agile-osjs menu results in a black window. Node red editor works normally

**Comment by nopbyte** [comment]
hi @dpap,

it seems that (most likely due to security integration) now the dashboard and the ui are in (http://resin.local:1880/api/ui/ and http://resin.local:1880/api/) instead of the root folder of the node-red Web server So, what you can do to reach the dashboard or the ui for now, is to open the urls I wrote to see the ui and the dashboard now.  

Also, you normally get black screens in the OS.js version that we have whenever there seems to be something wrong with the request. BUT you can check whether the site is displaying some kind of error by trying to select the black area with the mouse (then you should see the actual error).

**Comment by dpap** [comment]
hi @nopbyte 

When I open the dashboard I get "Cannot GET /dash/" and the UI "Cannot GET /ui/"
After adding resin.local to /etc/hosts (because my router is not allocating that name) I can see the dashboard. Also the ip address works too.  http://resin.local:1880/api/ returns  "Cannot GET /api/"

**Comment by cskiraly** [comment]
@nopbyte is there any reason these should be under /api? Would it be simple to move them back to their old URL?

**Comment by nopbyte** [comment]
@dpap, sorry I mean that the dashboard is under /api/dash.
@cskiraly, I am not an expert on how the dashboard works. But it seems this is a side-effect of including node-red in the new secure-node-red app and instructing it to have a route for the APIs exposed by nodes (for example, when you have an http node the path is mounted in /api). I am not sure what happens if I set this to /, I will try...

**Comment by cskiraly** [comment]
Fixed in https://github.com/Agile-IoT/agile-osjs/commit/001c966682cf510d64b7e3a60a9cd97a0908003b and
https://github.com/Agile-IoT/secure-nodered/commit/6054b9ca7e2b6051ff2f2cac75d4a48a97b12571
